WIP

diff --git a/Ch06 - Working with EC2 Instances/ghost-blog.yaml b/Ch06 - Working with EC2 Instances/ghost-blog.yaml
--- a/Ch06 - Working with EC2 Instances/ghost-blog.yaml
+++ b/Ch06 - Working with EC2 Instances/ghost-blog.yaml
@@ -181,8 +181,10 @@ Resources:
         - Key: Application
           Value:
             Ref: "AWS::StackName"
+    DependsOn: GhostVpc
   PubSubnetDefaultRoute:
     Type: "AWS::EC2::Route"
+    DependsOn: InternetGateway
     Properties:
       RouteTableId:
         Ref: PubSubnetRouteTable
@@ -228,6 +230,7 @@ Resources:
         - Key: Application
           Value:
             Ref: "AWS::StackName"
+    DependsOn: GhostVpc
   DbSubnet2:
     Type: "AWS::EC2::Subnet"
     Properties:
@@ -247,6 +250,7 @@ Resources:
         - Key: Application
           Value:
             Ref: "AWS::StackName"
+    DependsOn: GhostVpc
   InternetGateway:
     Type: "AWS::EC2::InternetGateway"
   InternetGatewayVPCAttachment:
@@ -275,6 +279,7 @@ Resources:
       PolicyName: SESSendPolicy
       Users:
         - Ref: GhostSesUser
+    DependsOn: GhostSesUser
   GhostSesUser:
     Type: "AWS::IAM::User"
     Properties:
@@ -304,43 +309,8 @@ Resources:
         - IpProtocol: tcp
           FromPort: "22"
           ToPort: "22"
-          CidrIp: 0.0.0.0/0
-        # - IpProtocol: tcp
-        #   FromPort: 80
-        #   ToPort: 80
-        #   CidrIp: 38.99.136.178/32
-        # - IpProtocol: tcp
-        #   FromPort: 443
-        #   ToPort: 443
-        #   CidrIp: 38.99.136.178/32
-        # - IpProtocol: tcp
-        #   FromPort: 80
-        #   ToPort: 80
-        #   CidrIp: 72.15.59.210/32
-        # - IpProtocol: tcp
-        #   FromPort: 443
-        #   ToPort: 443
-        #   CidrIp: 72.15.59.210/32
-        # - IpProtocol: tcp
-        #   FromPort: 80
-        #   ToPort: 80
-        #   CidrIp: 35.182.69.133/32
-        # - IpProtocol: tcp
-        #   FromPort: 443
-        #   ToPort: 443
-        #   CidrIp: 35.182.69.133/32
-        # - IpProtocol: tcp
-        #   FromPort: 22
-        #   ToPort: 22
-        #   CidrIp: 38.99.136.178/32
-        # - IpProtocol: tcp
-        #   FromPort: 22
-        #   ToPort: 22
-        #   CidrIp: 72.15.59.210/32
-        # - IpProtocol: tcp
-        #   FromPort: 22
-        #   ToPort: 22
-        #   CidrIp: 38.99.136.178/32
+          CidrIp:
+            Ref: SSHLocation
       VpcId:
         Ref: GhostVpc
   GhostDbEc2SecurityGroup:
@@ -349,21 +319,22 @@ Resources:
       GroupDescription: Open database for access
       SecurityGroupIngress:
         - IpProtocol: tcp
-          FromPort: 3306
-          ToPort: 3306
+          FromPort: "3306"
+          ToPort: "3306"
           SourceSecurityGroupId:
             Ref: GhostServerSecurityGroup
       VpcId:
         Ref: GhostVpc
   GhostDbInstance:
     Type: "AWS::RDS::DBInstance"
+    DependsOn: GhostDbEc2SecurityGroup
     Properties:
       DBName:
         Ref: DbName
       Engine: MySQL
       EngineVersion: "5.7"
-      BackupRetentionPeriod: 7
-      MultiAZ: false
+      BackupRetentionPeriod: "7"
+      MultiAZ: "false"
       MasterUsername: root
       MasterUserPassword:
         Ref: DbRootPassword
@@ -406,48 +377,35 @@ Resources:
         install_and_enable_cfn_hup:
           files:
             /etc/cfn/cfn-hup.conf:
-              content:
-                "Fn::Join":
-                  - ""
-                  - - "[main]\n"
-                    - "stack="
-                    - Ref: "AWS::StackId"
-                    - "\n"
-                    - "region="
-                    - Ref: "AWS::Region"
-                    - "\n"
-                    - "interval=5\n"
+              content: !Sub |
+                [main]
+                stack=${AWS::StackId}
+                region=${AWS::Region}
+                interval=5
+
               mode: "000400"
               owner: root
               group: root
             /etc/cfn/hooks.d/cfn-auto-reloader.conf:
-              content:
-                "Fn::Join":
-                  - ""
-                  - - "[cfn-auto-reloader-hook]\n"
-                    - "triggers=post.update\n"
-                    - "path=Resources.GhostServer.Metadata.AWS::CloudFormation::Init"
-                    - "action=/usr/local/bin/cfn-init -v "
-                    - " --stack "
-                    - Ref: "AWS::StackName"
-                    - " --resource GhostServer"
-                    - " --configsets full_install "
-                    - " --region "
-                    - Ref: "AWS::Region"
-                    - "\n"
-                    - "runas=root\n"
+              content: !Sub |
+                [cfn-auto-reloader-hook]
+                triggers=post.update
+                path=Resources.GhostServer.Metadata.AWS::CloudFormation::Init
+                action=/usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource GhostServer --configsets full_install --region ${AWS::Region}
+                runas=root
+
             /lib/systemd/system/cfn-hup.service:
-              content:
-                "Fn::Join":
-                  - ""
-                  - - "[Unit]\n"
-                    - "Description=cfn-hup daemon\n\n"
-                    - "[Service]\n"
-                    - "Type=simple\n"
-                    - "ExecStart=/usr/local/bin/cfn-hup\n"
-                    - "Restart=always\n\n"
-                    - "[Install]\n"
-                    - "WantedBy=multi-user.target"
+              content: |
+                [Unit]
+                Description=cfn-hup daemon
+
+                [Service]
+                Type=simple
+                ExecStart=/usr/local/bin/cfn-hup
+                Restart=always
+
+                [Install]
+                WantedBy=multi-user.target
           commands:
             01enable_cfn_hup:
               command: systemctl enable cfn-hup.service
@@ -456,187 +414,65 @@ Resources:
         prep_ghost:
           files:
             /tmp/setup.mysql:
-              content:
-                "Fn::Join":
-                  - ""
-                  - - "CREATE DATABASE IF NOT EXISTS "
-                    - Ref: DbName
-                    - ";\n"
-                    - "CREATE USER IF NOT EXISTS '"
-                    - Ref: DbUser
-                    - "'@'%' IDENTIFIED BY '"
-                    - Ref: DbPassword
-                    - "';\n"
-                    - "GRANT ALL ON "
-                    - Ref: DbName
-                    - ".* TO '"
-                    - Ref: DbUser
-                    - "'@'%';\n"
-                    - "FLUSH PRIVILEGES;\n"
+              content: !Sub |
+                CREATE DATABASE IF NOT EXISTS ${DbName};
+                CREATE USER IF NOT EXISTS '${DbUser}'@'%' IDENTIFIED BY '${DbPassword}';
+                GRANT ALL ON ${DbName}.* TO '${DbUser}'@'%';
+                FLUSH PRIVILEGES;
+
               mode: "000644"
               owner: root
               group: root
             /usr/local/bin/run_mysql_setup:
-              content:
-                "Fn::Join":
-                  - ""
-                  - - "#!/bin/bash\n"
-                    - "apt-get upgrade nginx mysql-client-5.7 -y\n"
-                    - "mysql -h "
-                    - "Fn::GetAtt":
-                        - GhostDbInstance
-                        - Endpoint.Address
-                    - " -u root -p"
-                    - Ref: DbRootPassword
-                    - " < /tmp/setup.mysql > /dev/null 2>&1\n"
-                    - "rm /tmp/setup.mysql\n"
+              content: !Sub |
+                #!/bin/bash
+                apt-get upgrade nginx mysql-client-5.7 -y
+                mysql -h ${GhostDbInstance.Endpoint.Address} -u root -p ${DbRootPassword} < /tmp/setup.mysql > /dev/null 2>&1
+
               mode: "000700"
               owner: root
               group: root
             /usr/local/bin/prep_and_install_ghost:
-              content:
-                "Fn::Join":
-                  - ""
-                  - - "#!/bin/bash\n"
-                    - "export GHOSTDIR=/var/www/ghost\n"
-                    - "export MAIL_PWD=`(echo -en '\\x02'; echo -n 'SendRawEmail' | openssl dgst -sha256 -hmac "
-                    - "Fn::GetAtt":
-                        - GhostSesUserAccessKey
-                        - SecretAccessKey
-                    - " -binary) | openssl enc -base64`\n"
-                    - "(id ghostuser > /dev/null 2>&1 && echo ghostuser exists...) "
-                    - "  || (useradd --user-group --create-home ghostuser && echo creating ghostuser...)\n"
-                    - "( [[ `groups ghostuser | awk '{print $4}'` == sudo ]] && echo ghostuser has sudo access...) "
-                    - "  || (usermod -aG sudo ghostuser && echo giving ghostuser sudo access...)\n"
-                    - "( [[ -f /etc/sudoers.d/ghostuser ]] && echo ghostuser can execute sudo w/o password) "
-                    - "  || (echo 'ghostuser ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/ghostuser && echo allowing ghostuser to execute sudo w/o password as required by cli...)\n"
-                    - "(node -v > /dev/null 2>&1 && echo node installed...) "
-                    - "  || (curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash && echo node repo configured)\n"
-                    - "node -v > /dev/null 2>&1 "
-                    - "  || (sudo apt-get install -y nodejs && echo node installed)\n"
-                    - "(ghost version && echo ghost present...) "
-                    - "  || (sudo npm install ghost-cli@latest -g && echo ghost installed...)\n"
-                    - "( [[ -d $GHOSTDIR ]] && echo $GHOSTDIR directory exists...) "
-                    - "  || (sudo mkdir -p $GHOSTDIR && echo ghost app directory created)\n"
-                    - "( [[ `stat -c %U $GHOSTDIR` == ghostuser ]] && [[ `stat -c %G $GHOSTDIR` == ghostuser ]] && echo $GHOSTDIR ownership correct...) "
-                    - "  || (sudo chown ghostuser:ghostuser $GHOSTDIR && echo ghost ownership set...)\n"
-                    - "( [[ `stat -c %a $GHOSTDIR` == 775 ]] && echo $GHOSTDIR permissions correct...) "
-                    - "  || (sudo chmod 775 $GHOSTDIR && echo $GHOSTDIR permissions set...)\n"
-                    - "if [[ -f config.production.json ]]; then\n"
-                    - "echo ghost present...\n"
-                    - "else\n"
-                    - "echo ghost not present, installing...\n"
-                    - 'su - ghostuser -c "cd /var/www/ghost && ghost install '
-                    - "--verbose "
-                    - "--url https://"
-                    - Ref: DomainName
-                    - " "
-                    - "--ip 0.0.0.0 "
-                    - "--dbhost "
-                    - "Fn::GetAtt":
-                        - GhostDbInstance
-                        - Endpoint.Address
-                    - " "
-                    - "--dbuser "
-                    - Ref: DbUser
-                    - " "
-                    - "--dbpass "
-                    - Ref: DbPassword
-                    - " "
-                    - "--dbname "
-                    - Ref: DbName
-                    - " "
-                    - "--mail SMTP "
-                    - "--mailuser "
-                    - Ref: GhostSesUserAccessKey
-                    - " "
-                    - "--mailpass $MAIL_PWD "
-                    - "--mailhost "
-                    - Ref: SesSmtpEndpoint
-                    - " "
-                    - "--mailport 587 "
-                    - "--sslemail "
-                    - Ref: SslEmail
-                    - " "
-                    - "--process systemd "
-                    - "--no-prompt --auto\"\n"
-                    - 'su - ghostuser -c "cd $GHOSTDIR && ghost config mail.from '
-                    - Ref: FromAddress
-                    - "\"\n"
-                    - "if [ -f $GHOSTDIR/system/files/www."
-                    - Ref: DomainName
-                    - ".conf ]; then\n"
-                    - "echo SSL for www configured...\n"
-                    - "else\n"
-                    - "echo generating cert and configuring nginx for www...\n"
-                    - 'su - ghostuser -c "cd $GHOSTDIR && ghost config url '
-                    - "Fn::Join":
-                        - .
-                        - - "https://www"
-                          - Ref: DomainName
-                    - "\"\n"
-                    - 'su - ghostuser -c "cd $GHOSTDIR && ghost setup nginx ssl --sslemail '
-                    - Ref: SslEmail
-                    - "\"\n"
-                    - 'su - ghostuser -c "cd $GHOSTDIR && ghost config url '
-                    - "Fn::Join":
-                        - ""
-                        - - "https://"
-                          - Ref: DomainName
-                    - "\"\n"
-                    - "awk '!/proxy_set_header/' $GHOSTDIR/system/files/"
-                    - "Fn::Join":
-                        - .
-                        - - www
-                          - Ref: DomainName
-                          - conf
-                    - " > "
-                    - "Fn::Join":
-                        - .
-                        - - /tmp/www
-                          - Ref: DomainName
-                          - conf
-                    - "\n"
-                    - "awk '!/proxy_set_header/' $GHOSTDIR/system/files/"
-                    - "www."
-                    - Ref: DomainName
-                    - "-ssl.conf"
-                    - " > "
-                    - "/tmp/www."
-                    - Ref: DomainName
-                    - "-ssl.conf"
-                    - "\n"
-                    - "sed -i 's/proxy_pass.*/return 301 https:\\/\\/"
-                    - Ref: DomainName
-                    - "\\$request_uri;/' /tmp/www."
-                    - Ref: DomainName
-                    - ".conf\n"
-                    - "sed -i 's/proxy_pass.*/return 301 https:\\/\\/"
-                    - Ref: DomainName
-                    - "\\$request_uri;/' /tmp/www."
-                    - Ref: DomainName
-                    - "-ssl.conf\n"
-                    - "mv /tmp/www."
-                    - Ref: DomainName
-                    - ".conf $GHOSTDIR/system/files/www."
-                    - Ref: DomainName
-                    - ".conf\n"
-                    - "mv /tmp/www."
-                    - Ref: DomainName
-                    - "-ssl.conf $GHOSTDIR/system/files/www."
-                    - Ref: DomainName
-                    - "-ssl.conf\n"
-                    - "chown ghostuser:ghostuser $GHOSTDIR/system/files/www."
-                    - Ref: DomainName
-                    - ".conf\n"
-                    - "chown ghostuser:ghostuser $GHOSTDIR/system/files/www."
-                    - Ref: DomainName
-                    - "-ssl.conf\n"
-                    - "nginx -t\n"
-                    - "nginx -s reload\n"
-                    - "fi\n"
-                    - "su - ghostuser -c \"cd $GHOSTDIR && ghost restart\"\n"
-                    - "fi\n"
+              content: !Sub |
+                #!/bin/bash
+                export GHOSTDIR=/var/www/ghost
+                export MAIL_PWD=`(echo -en '\\x02'; echo -n 'SendRawEmail' | openssl dgst -sha256 -hmac ${GhostSesUserAccessKey.SecretAccessKey} -binary) | openssl enc -base64`
+                (id ghostuser > /dev/null 2>&1 && echo ghostuser exists...) || (useradd --user-group --create-home ghostuser && echo creating ghostuser...)
+                ( [[ `groups ghostuser | awk '{print $4}'` == sudo ]] && echo ghostuser has sudo access...) || (usermod -aG sudo ghostuser && echo giving ghostuser sudo access...)
+                ( [[ -f /etc/sudoers.d/ghostuser ]] && echo ghostuser can execute sudo w/o password) || (echo 'ghostuser ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/ghostuser && echo allowing ghostuser to execute sudo w/o password as required by cli...)
+                (node -v > /dev/null 2>&1 && echo node installed...) || (curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash && echo node repo configured)
+                node -v > /dev/null 2>&1 || (sudo apt-get install -y nodejs && echo node installed)
+                (ghost version && echo ghost present...) || (sudo npm install ghost-cli@latest -g && echo ghost installed...)
+                ( [[ -d $GHOSTDIR ]] && echo $GHOSTDIR directory exists...) || (sudo mkdir -p $GHOSTDIR && echo ghost app directory created)
+                ( [[ `stat -c %U $GHOSTDIR` == ghostuser ]] && [[ `stat -c %G $GHOSTDIR` == ghostuser ]] && echo $GHOSTDIR ownership correct...) || (sudo chown ghostuser:ghostuser $GHOSTDIR && echo ghost ownership set...)
+                ( [[ `stat -c %a $GHOSTDIR` == 775 ]] && echo $GHOSTDIR permissions correct...) || (sudo chmod 775 $GHOSTDIR && echo $GHOSTDIR permissions set...)
+                if [[ -f config.production.json ]]; then
+                echo ghost present...
+                else
+                echo ghost not present, installing...
+                su - ghostuser -c "cd /var/www/ghost && ghost install --verbose --url https://${DomainName} --ip 0.0.0.0 --dbhost ${GhostDbInstance.Endpoint.Address} --dbuser ${DbUser} --dbpass ${DbPassword} --dbname ${DbName} --mail SMTP --mailuser ${GhostSesUserAccessKey} --mailpass $MAIL_PWD --mailhost ${SesSmtpEndpoint} --mailport 587 --sslemail ${SslEmail} --process systemd --no-prompt --auto"
+                su - ghostuser -c "cd $GHOSTDIR && ghost config mail.from ${FromAddress}"
+                if [ -f $GHOSTDIR/system/files/www.${DomainName}.conf ]; then
+                echo SSL for www configured...
+                else
+                echo generating cert and configuring nginx for www...
+                su - ghostuser -c "cd $GHOSTDIR && ghost config url https://www.${DomainName}"
+                su - ghostuser -c "cd $GHOSTDIR && ghost setup nginx ssl --sslemail ${SslEmail}"
+                su - ghostuser -c "cd $GHOSTDIR && ghost config url https://${DomainName}"
+                awk '!/proxy_set_header/' $GHOSTDIR/system/files/www.${DomainName}.conf > /tmp/www.${DomainName}.conf
+                awk '!/proxy_set_header/' $GHOSTDIR/system/files/www.${DomainName}-ssl.conf > /tmp/www.${DomainName}-ssl.conf
+                sed -i 's/proxy_pass.*/return 301 https:\\/\\/${DomainName}\\$request_uri;/' /tmp/www.${DomainName}.conf
+                sed -i 's/proxy_pass.*/return 301 https:\\/\\/${DomainName}\\$request_uri;/' /tmp/www.${DomainName}-ssl.conf
+                mv /tmp/www.${DomainName}.conf $GHOSTDIR/system/files/www.${DomainName}.conf
+                mv /tmp/www.${DomainName}-ssl.conf $GHOSTDIR/system/files/www.${DomainName}-ssl.conf
+                chown ghostuser:ghostuser $GHOSTDIR/system/files/www.${DomainName}.conf
+                chown ghostuser:ghostuser $GHOSTDIR/system/files/www.${DomainName}-ssl.conf
+                nginx -t
+                nginx -s reload
+                fi
+                su - ghostuser -c "cd $GHOSTDIR && ghost restart"
+                fi
+
               mode: "000700"
               owner: root
               group: root
@@ -694,8 +530,10 @@ Resources:
               - "         --region "
               - Ref: "AWS::Region"
               - "\n"
+
   GhostServerRootRecordSet:
     Type: "AWS::Route53::RecordSet"
+    DependsOn: GhostServerEip
     Properties:
       HostedZoneId:
         Ref: HostedZoneId
