WIP

diff --git a/Ch06 - Working with EC2 Instances/ghost-blog.yaml b/Ch06 - Working with EC2 Instances/ghost-blog.yaml
--- a/Ch06 - Working with EC2 Instances/ghost-blog.yaml
+++ b/Ch06 - Working with EC2 Instances/ghost-blog.yaml
@@ -179,7 +179,7 @@ Resources:
     Type: AWS::RDS::DBSubnetGroup
     Properties:
       DBSubnetGroupDescription: database subnet group
-      DBSubnetGroupName: GhostDbSubnetGroup
+      DBSubnetGroupName: !Sub ${AWS::StackName}GhostDbSubnetGroup
       SubnetIds:
         - !Ref DbSubnet1
         - !Ref DbSubnet2
@@ -225,13 +225,13 @@ Resources:
             Condition:
               StringEquals:
                 "ses:FromAddress": !Ref FromAddress
-      PolicyName: SESSendPolicy
+      PolicyName: !Sub ${AWS::StackName}SESSendPolicy
       Users:
         - !Ref GhostSesUser
   GhostSesUser:
     Type: AWS::IAM::User
     Properties:
-      UserName: !Sub ${AWS::Region}-ghost-ses
+      UserName: !Sub ${AWS::StackName}-${AWS::Region}-ghost-ses
   GhostSesUserAccessKey:
     Type: AWS::IAM::AccessKey
     Properties:
@@ -244,41 +244,54 @@ Resources:
         - IpProtocol: tcp
           FromPort: 80
           ToPort: 80
-          CidrIp: 38.99.136.178/32 # Klick Office
-        - IpProtocol: tcp
-          FromPort: 80
-          ToPort: 80
-          CidrIp: 72.15.59.210/32 # Klick Office
-        - IpProtocol: tcp
-          FromPort: 80
-          ToPort: 80
-          CidrIp: 35.182.69.133/32 # vpn.klick.com
+          CidrIp: 0.0.0.0/0
 
         - IpProtocol: tcp
           FromPort: 443
           ToPort: 443
-          CidrIp: 38.99.136.178/32
-        - IpProtocol: tcp
-          FromPort: 443
-          ToPort: 443
-          CidrIp: 72.15.59.210/32
-        - IpProtocol: tcp
-          FromPort: 443
-          ToPort: 443
-          CidrIp: 35.182.69.133/32
+          CidrIp: 0.0.0.0/0
 
         - IpProtocol: tcp
           FromPort: 22
           ToPort: 22
-          CidrIp: 38.99.136.178/32
-        - IpProtocol: tcp
-          FromPort: 22
-          ToPort: 22
-          CidrIp: 72.15.59.210/32
-        - IpProtocol: tcp
-          FromPort: 22
-          ToPort: 22
-          CidrIp: 35.182.69.133/32
+          CidrIp: 0.0.0.0/0
+
+        # - IpProtocol: tcp
+        #   FromPort: 80
+        #   ToPort: 80
+        #   CidrIp: 38.99.136.178/32 # Klick Office
+        # - IpProtocol: tcp
+        #   FromPort: 80
+        #   ToPort: 80
+        #   CidrIp: 72.15.59.210/32 # Klick Office
+        # - IpProtocol: tcp
+        #   FromPort: 80
+        #   ToPort: 80
+        #   CidrIp: 35.182.69.133/32 # vpn.klick.com
+        # - IpProtocol: tcp
+        #   FromPort: 443
+        #   ToPort: 443
+        #   CidrIp: 38.99.136.178/32
+        # - IpProtocol: tcp
+        #   FromPort: 443
+        #   ToPort: 443
+        #   CidrIp: 72.15.59.210/32
+        # - IpProtocol: tcp
+        #   FromPort: 443
+        #   ToPort: 443
+        #   CidrIp: 35.182.69.133/32
+        # - IpProtocol: tcp
+        #   FromPort: 22
+        #   ToPort: 22
+        #   CidrIp: 38.99.136.178/32
+        # - IpProtocol: tcp
+        #   FromPort: 22
+        #   ToPort: 22
+        #   CidrIp: 72.15.59.210/32
+        # - IpProtocol: tcp
+        #   FromPort: 22
+        #   ToPort: 22
+        #   CidrIp: 35.182.69.133/32
       VpcId: !Ref GhostVpc
   GhostDbEc2SecurityGroup:
     Type: AWS::EC2::SecurityGroup
@@ -322,6 +335,10 @@ Resources:
       - GhostServerWwwRecordSet
       - GhostServerWwwRecordSet
       - GhostDbInstance
+    # CreationPolicy:
+    #   ResourceSignal:
+    #     Count: 1
+    #     Timeout: PT5M
     Metadata:
       "AWS::CloudFormation::Init":
         configSets:
@@ -381,7 +398,7 @@ Resources:
               content: !Sub |
                 #!/bin/bash
                 apt-get upgrade nginx mysql-client-5.7 -y
-                mysql -h ${GhostDbInstance.Endpoint.Address} -u root -p ${DbRootPassword} < /tmp/setup.mysql > /dev/null 2>&1
+                mysql --host=${GhostDbInstance.Endpoint.Address} --user=root --password=${DbRootPassword} < /tmp/setup.mysql > /dev/null 2>&1
 
               mode: "000700"
               owner: root
@@ -390,16 +407,16 @@ Resources:
               content: !Sub |
                 #!/bin/bash
                 export GHOSTDIR=/var/www/ghost
-                export MAIL_PWD=`(echo -en '\\x02'; echo -n 'SendRawEmail' | openssl dgst -sha256 -hmac ${GhostSesUserAccessKey.SecretAccessKey} -binary) | openssl enc -base64`
-                (id ghostuser > /dev/null 2>&1 && echo ghostuser exists...) || (useradd --user-group --create-home ghostuser && echo creating ghostuser...)
-                ( [[ `groups ghostuser | awk '{print $4}'` == sudo ]] && echo ghostuser has sudo access...) || (usermod -aG sudo ghostuser && echo giving ghostuser sudo access...)
-                ( [[ -f /etc/sudoers.d/ghostuser ]] && echo ghostuser can execute sudo w/o password) || (echo 'ghostuser ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/ghostuser && echo allowing ghostuser to execute sudo w/o password as required by cli...)
-                (node -v > /dev/null 2>&1 && echo node installed...) || (curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash && echo node repo configured)
-                node -v > /dev/null 2>&1 || (sudo apt-get install -y nodejs && echo node installed)
-                (ghost version && echo ghost present...) || (sudo npm install ghost-cli@latest -g && echo ghost installed...)
-                ( [[ -d $GHOSTDIR ]] && echo $GHOSTDIR directory exists...) || (sudo mkdir -p $GHOSTDIR && echo ghost app directory created)
-                ( [[ `stat -c %U $GHOSTDIR` == ghostuser ]] && [[ `stat -c %G $GHOSTDIR` == ghostuser ]] && echo $GHOSTDIR ownership correct...) || (sudo chown ghostuser:ghostuser $GHOSTDIR && echo ghost ownership set...)
-                ( [[ `stat -c %a $GHOSTDIR` == 775 ]] && echo $GHOSTDIR permissions correct...) || (sudo chmod 775 $GHOSTDIR && echo $GHOSTDIR permissions set...)
+                export MAIL_PWD=`(echo -en '\x02'; echo -n 'SendRawEmail' | openssl dgst -sha256 -hmac ${GhostSesUserAccessKey.SecretAccessKey} -binary) | openssl enc -base64`
+                (id ghostuser > /dev/null 2>&1 && echo ghostuser exists...)   || (useradd --user-group --create-home ghostuser && echo creating ghostuser...)
+                ( [[ `groups ghostuser | awk '{print $4}'` == sudo ]] && echo ghostuser has sudo access...)   || (usermod -aG sudo ghostuser && echo giving ghostuser sudo access...)
+                ( [[ -f /etc/sudoers.d/ghostuser ]] && echo ghostuser can execute sudo w/o password)   || (echo 'ghostuser ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/ghostuser && echo allowing ghostuser to execute sudo w/o password as required by cli...)
+                (node -v > /dev/null 2>&1 && echo node installed...)   || (curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash && echo node repo configured)
+                node -v > /dev/null 2>&1   || (sudo apt-get install -y nodejs && echo node installed)
+                (ghost version && echo ghost present...)   || (sudo npm install ghost-cli@latest -g && echo ghost installed...)
+                ( [[ -d $GHOSTDIR ]] && echo $GHOSTDIR directory exists...)   || (sudo mkdir -p $GHOSTDIR && echo ghost app directory created)
+                ( [[ `stat -c %U $GHOSTDIR` == ghostuser ]] && [[ `stat -c %G $GHOSTDIR` == ghostuser ]] && echo $GHOSTDIR ownership correct...)   || (sudo chown ghostuser:ghostuser $GHOSTDIR && echo ghost ownership set...)
+                ( [[ `stat -c %a $GHOSTDIR` == 775 ]] && echo $GHOSTDIR permissions correct...)   || (sudo chmod 775 $GHOSTDIR && echo $GHOSTDIR permissions set...)
                 if [[ -f config.production.json ]]; then
                 echo ghost present...
                 else
@@ -415,8 +432,8 @@ Resources:
                 su - ghostuser -c "cd $GHOSTDIR && ghost config url https://${DomainName}"
                 awk '!/proxy_set_header/' $GHOSTDIR/system/files/www.${DomainName}.conf > /tmp/www.${DomainName}.conf
                 awk '!/proxy_set_header/' $GHOSTDIR/system/files/www.${DomainName}-ssl.conf > /tmp/www.${DomainName}-ssl.conf
-                sed -i 's/proxy_pass.*/return 301 https:\\/\\/${DomainName}\\$request_uri;/' /tmp/www.${DomainName}.conf
-                sed -i 's/proxy_pass.*/return 301 https:\\/\\/${DomainName}\\$request_uri;/' /tmp/www.${DomainName}-ssl.conf
+                sed -i 's/proxy_pass.*/return 301 https:\/\/${DomainName}\$request_uri;/' /tmp/www.${DomainName}.conf
+                sed -i 's/proxy_pass.*/return 301 https:\/\/${DomainName}\$request_uri;/' /tmp/www.${DomainName}-ssl.conf
                 mv /tmp/www.${DomainName}.conf $GHOSTDIR/system/files/www.${DomainName}.conf
                 mv /tmp/www.${DomainName}-ssl.conf $GHOSTDIR/system/files/www.${DomainName}-ssl.conf
                 chown ghostuser:ghostuser $GHOSTDIR/system/files/www.${DomainName}.conf
@@ -435,8 +452,8 @@ Resources:
               command: /usr/local/bin/run_mysql_setup
             02setup_ghost:
               command: /usr/local/bin/prep_and_install_ghost
-            # 03cleanup:
-            #   command: rm /usr/local/bin/run_mysql_setup /usr/local/bin/prep_and_install_ghost
+            03cleanup:
+              command: rm /usr/local/bin/run_mysql_setup /usr/local/bin/prep_and_install_ghost
     Properties:
       AvailabilityZone:
         !FindInMap [SubnetAvailabilityZone, PubSubnet, AvailabilityZone]
@@ -496,7 +513,7 @@ Outputs:
     Export:
       Name: !Sub ${AWS::StackName}-GhostAdminUrl
   InstanceIPAddress:
-    Description: IP Address to use to SSH to the Ghsot instance
+    Description: IP Address to use to SSH to the Ghost instance
     Value:
       Ref: GhostServerEip
     Export:
